name: flutterbrocli
description: Flutter Bro command line tools.
version: 0.1.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3

dev_dependencies:
  test: ^1.14.4

  dart_code_metrics: ^3.1.0